language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test
after_success:
  - cover -report coveralls
after_script:
  - echo ${TRAVIS_TEST_RESULT} | grep -F -q '/.cpanm/build.log' && tail -n50 /home/travis/.cpanm/build.log
notifications:
  irc:
    channels:
      - "irc.freenode.net#bayadev"
    on_success: change
    on_failure: always
