name: windows_latest

on:
  push:
    branches:
      - main
      - '**windows**'
    tags-ignore:
      - '*'

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install Windows Specific Module
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Win32
      - name: Perldoc
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Pod::Perldoc
      - name: test
        run: |
          ls -la "C:\Strawberry\perl\lib\auto"
          echo $PATH
          perldoc -l Win32
